namespace XenoUI.Core.Pillars;

/// <summary>
/// A stack-only descriptor of a UI element. 
/// Zero heap allocations. Generated purely to instruct the Reconciler.
/// </summary>
public ref struct Blueprint
{
    public uint Id;               // Stable ID generated by Source Generators / Caller Line Number
    public uint TypeId;           // Enum or fast ID for type (e.g., Button, Text, NativeMap)
    
    // Layout & Math
    public float  X, Y, Width, Height;

    // Styling offset (Points to the Theme Arena!)
    public int ThemeOffsetId;
    
    // Tells the Reconciler how many children this element has(to follow).
    public int ChildCount;
}